### ISSUE TITLE
unknown function : <SNR>16_translate_replace

### ISSUE THREAD

**Issue by teto** [farseer90718/vim-translator#1]
Tried to install the plugin with vim-plug, on neovim launch, I get

```
line   55 :
E117: unknown function : <SNR>16_translate_replace
```

**Comment by lsrdg** [comment]
Almost the same here:
`line   55:
E117: Unknown function: <SNR>21_translate_replace`
There is this error while launching neovim, but the plugin is actually working pretty well. (:

EDIT: forgot to mention that the plugin was intalled with vim-plug, exactecly as @teto.

**Comment by suoto** [comment]
Remove or comment [translator.vim line 55](https://github.com/blindFS/vim-translator/blob/master/plugin/translator.vim#L55). This plugin seems dead as such a simple issue hasn't been fixed in 2 years...
